app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\VerifyEmailController::verifyUserEmail

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_forgot_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request

app_check_email:
    path: /reset-password/check-email
    controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
    path: /reset-password/reset/{token}
    controller: App\Controller\ResetPasswordController::reset

# --- Ajout des routes pour les livres ---

livre_list:
    path: /livres
    controller: App\Controller\LivreController::index

livre_detail:
    path: /livre/{id}
    controller: App\Controller\LivreController::detail
    requirements:
        id: '\d+'

# --- Routes panier ---

panier_ajouter:
    path: /panier/ajouter/{id}
    controller: App\Controller\PanierController::ajouter
    requirements:
        id: '\d+'

panier_supprimer:
    path: /panier/supprimer/{id}
    controller: App\Controller\PanierController::supprimer
    requirements:
        id: '\d+'

panier:
    path: /panier
    controller: App\Controller\PanierController::afficher

commande_valider_panier:
    path: /commande/valider-panier
    controller: App\Controller\CommandeController::validerPanier

# --- Routes commandes (consultation) ---

commande_index:
    path: /commandes
    controller: App\Controller\CommandeController::index

commande_show:
    path: /commande/{id}
    controller: App\Controller\CommandeController::show
    requirements:
        id: '\d+'
